### PR TITLE
Fix background forking on POSIX, add timestamp

### PR DESCRIPTION
**Pull request by jay-star**
(Please ignore my commented Azure changes, I don't know how to exclude them from PR, nor how to exclude my previous PR: #27)

- My use case requires foggycam to run in the background. Every previous commit would work great if process was in foreground, but forking to background caused ffmpeg to fail every time (`python3 start.py &`) - this fixes that behavior with `subprocess` and additional args.
- We now run ffmpeg twice in order to add timestamp overlay (read TODO comments!)
- Save final video as datetime.mp4 instead of random hash

### CODE REVIEW

**Comment by dend** [comment]
This is interesting, thank you @jay-star - I will review this after the holidays and we can see what we can do to get this contribution merged.

**Comment by jay-star** [comment]
> This is interesting, thank you @jay-star - I will review this after the holidays and we can see what we can do to get this contribution merged.

Thanks! I could really use some help (see TODO) to chain the drawtext into a single call to ffmpeg, instead of 2 like I am doing. Literally doubling the load on each video created. 

Also, I suggest we maybe do ultrafast preset for ffmpeg? Considering there are a lot of people running this on weak CPUs (I run it on Synology DSM)

**Comment by jay-star** [comment]
> This is interesting, thank you @jay-star - I will review this after the holidays and we can see what we can do to get this contribution merged.

Friendly reminder!

**Comment by dend** [comment]
@jay-star still on my radar, just haven't had time to review and build the changes - will get to it in the coming week!

**Comment by dend** [comment]
Thank you for the contribution! I've just released a new version of the application, and this PR is no longer applicable. For future pull request, I recommend opening an issue first so we can discuss enhancements before those can be implemented.

**Pull request closed without merging**
